// Generates the public, dependency-free pages. Run with Node 20+.
import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { works } from '../mercy/assets/needs.mjs';
import { resources } from '../mercy/assets/resources.mjs';
import { escapeHTML as e } from '../mercy/assets/core.mjs';

const output = fileURLToPath(new URL('../mercy/', import.meta.url));
mkdirSync(output,{recursive:true});
const nav = [ ['board','index.html','Explore needs'], ['resources','resources.html','Find resources'], ['works','works.html','The 14 works'], ['project','project.html','The project'], ['corner','my-corner.html','My corner'] ];
function layout(page,title,description,body) {
  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="${e(description)}"><meta name="referrer" content="no-referrer">
<meta http-equiv="Content-Security-Policy" content="default-src 'self'; script-src 'self'; style-src 'self'; img-src 'self' data:; connect-src 'none'; base-uri 'none'; form-action 'none'">
<meta name="theme-color" content="#184e43"><meta property="og:title" content="${e(title)} | Endless AI Mercy Network"><meta property="og:description" content="${e(description)}"><meta property="og:type" content="website">
<title>${e(title)} | Endless AI Mercy Network</title><link rel="icon" href="assets/favicon.svg" type="image/svg+xml"><link rel="stylesheet" href="assets/styles.css"><script type="module" src="assets/app.mjs"></script>
</head><body data-page="${page}">
<a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="shell header-inner"><a class="brand" href="../index.html" aria-label="Endless AI home"><span class="brand-symbol" aria-hidden="true">∞</span><span><strong>Endless AI</strong><small>Mercy Network</small></span></a><nav class="nav" aria-label="Main navigation">${nav.map(([id,url,label])=>`<a href="${url}"${id===page?' aria-current="page"':''}>${label}</a>`).join('')}</nav><button class="button primary" data-action="draft">+ Draft a need</button></div></header>
<div class="preview-bar"><strong>Open community preview</strong> · Example people and stories · No payments collected. <a href="project.html">See the plan</a></div>
<main class="shell" id="main">${body}</main>
<footer class="site-footer"><div class="shell footer-inner"><div><span class="footer-brand">Endless AI · Mercy Network</span><p>Rooted in the fourteen Catholic works of mercy. Open to neighbors of every faith and background. Help is never conditional on belief.</p></div><div class="footer-links"><a href="project.html">About the project</a><a href="my-corner.html">Your saved drafts</a><a href="https://github.com/Maestro-Student777/endless-ai-product-realization" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></div></footer>
<dialog id="modal" aria-labelledby="modal-title"></dialog><div class="toast" id="notice" role="status" aria-live="polite"></div>
</body></html>\n`;
}
const board = `
<section class="hero"><div><div class="eyebrow">Every neighbor has something to give</div><h1>A little help.<br><em>A real difference.</em></h1><p class="lead">A meal. A mattress. A way to get to work. Find a need that speaks to you, and imagine what we could make possible together.</p><div class="actions"><a class="button primary" href="#explore">Explore the needs <span aria-hidden="true">↓</span></a><button class="button" data-action="draft">I could use some help</button></div><p class="hero-note">Start with a neighbor. Grow a community. Open in any modern browser.</p></div><aside class="hero-card"><div class="eyebrow">Mercy is something we do</div><h2>There is more than<br>one way to give.</h2><p>A person asking for help may also have a skill to share, a story to tell, or a prayer to offer.</p><div class="ways"><span><b aria-hidden="true">$</b> A small gift</span><span><b aria-hidden="true">◷</b> Your time</span><span><b aria-hidden="true">◇</b> Something useful</span><span><b aria-hidden="true">✝</b> A prayer</span></div></aside></section>
<div class="section-heading" id="explore"><div><h2>Meet a need. See a person.</h2><p>Explore illustrative stories, then follow real resources for practical help.</p></div><a class="back" href="resources.html">Need help today? Find resources →</a></div>
<div class="board-layout"><aside class="sidebar" aria-label="Filter by work of mercy"><button class="work-filter active" data-work="all" aria-pressed="true">All needs</button><div id="desktop-works"></div><div class="sidebar-callout"><strong>Small gifts have a place.</strong><p>Five dollars can be meaningful. So can a conversation, an item, or an hour of your time.</p><a href="works.html">Explore the 14 works →</a></div></aside><section aria-label="Needs board"><div class="toolbar"><label class="field search">Search stories<input type="search" id="need-search" placeholder="Food, gas, a mattress…" autocomplete="off"></label><label class="field">I can offer<select id="need-kind"><option value="all">Any kind of help</option><option value="small">$25 or less</option><option value="money">Money</option><option value="time">Time</option><option value="goods">An item</option><option value="prayer">Prayer</option></select></label><label class="field">Sort by<select id="need-sort"><option value="featured">Story order</option><option value="low">Smallest goal first</option><option value="high">Largest goal first</option></select></label><label class="field mobile-work">Work of mercy<select id="work-filter"><option value="all">All works of mercy</option></select></label></div><p class="result-count" id="need-count" role="status" aria-live="polite"></p><div class="cards" id="need-cards"><noscript><div class="empty"><h2>Explore help without an account.</h2><p>Enable JavaScript to browse the example profiles and save personal drafts. The resource guide and project page work without it.</p><a class="button" href="resources.html">Find resources</a></div></noscript></div></section></div>`;

const resourceCards = resources.map(r => `<article class="resource-card" data-resource="${r.id}"><p class="provider">${e(r.organization)}</p><h3><a href="${e(r.url)}" target="_blank" rel="noopener noreferrer">${e(r.name)}</a></h3><div class="resource-meta"><span class="tag">${e(r.area)}</span><span class="tag">${e(r.kind)}</span></div><p>${e(r.description)}</p><p class="cost">${e(r.cost)}</p><a class="source-link" href="${e(r.url)}" target="_blank" rel="noopener noreferrer"><span>Open ${e(new URL(r.url).hostname.replace(/^www\./,''))}</span><span aria-hidden="true">↗</span></a></article>`).join('\n');
const resourcePage = `<section class="intro"><div class="eyebrow">A place to start, today</div><h1>Help is already out there.</h1><p>Find useful programs, trusted guides, and people who may be able to help. Every link takes you to the organization’s own website.</p></section><div class="resource-toolbar toolbar no-print"><label class="field search">What are you looking for?<input type="search" id="resource-search" placeholder="Food, furniture, mortgage, work…" autocomplete="off"></label><label class="field">Kind of help<select id="resource-topic"><option value="all">Every kind of help</option></select></label><label class="field">Where it applies<select id="resource-area"><option value="all">All service areas</option><option value="Minnesota">Minnesota-specific</option><option value="United States">United States-wide</option><option value="Online">Online faith resources</option></select></label></div><p class="result-count" id="resource-count" role="status" aria-live="polite">${resources.length} resources · Source links reviewed September 12, 2026</p><div class="resources-grid">${resourceCards}<div class="empty" id="resource-empty" hidden><h2>Try a broader search.</h2><p>No resource matches these filters. Choose another area or kind of help.</p></div></div><p class="source-note">All of these pages are free to open. Services may have eligibility requirements, limited availability, or fees. Check directly with the provider. Listings are referrals and do not imply a partnership with Endless AI. For local referrals in the U.S., you can also <a href="tel:211">call 211</a>.</p>`;

const worksPage = `<section class="intro"><div class="eyebrow">Faith expressed through care</div><h1>Fourteen ways to show up.</h1><p>The seven corporal works address bodily needs. The seven spiritual works care for the inner life. Together they inspire this network of practical help, presence, and prayer.</p></section>${['corporal','spiritual'].map(f=>`<section class="works-section"><div class="section-heading"><div><h2>The ${f} works</h2><p>${f==='corporal'?'Food, shelter, care, and companionship in the realities of life.':'Compassion, understanding, forgiveness, and faith in everyday relationships.'}</p></div></div><div class="works-grid">${works.filter(w=>w.family===f).map((w,i)=>`<article class="work-card"><span class="work-number" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><div><h3>${e(w.name)}</h3><p>${e(w.action)}</p><a href="index.html?work=${w.id}#explore">Explore this work of mercy →</a></div></article>`).join('')}</div></section>`).join('')}<p class="source-note">Catholic foundation: the list in Appendix B of the <a href="https://www.vatican.va/archive/compendium_ccc/documents/archive_2005_compendium-ccc_en.html" target="_blank" rel="noopener noreferrer">Compendium of the Catechism of the Catholic Church ↗</a>. Explore further reflections on the <a href="https://www.usccb.org/beliefs-and-teachings/how-we-teach/new-evangelization/jubilee-of-mercy/the-spiritual-works-of-mercy" target="_blank" rel="noopener noreferrer">USCCB website ↗</a>. Practical examples here are our own suggestions; participation in religious activities is always voluntary.</p>`;

const projectPage = `<section class="project-lead"><div><div class="eyebrow">An Endless AI community project · EAI-MERCY-0001</div><h1>Connect a person’s need<br>with another’s kindness.</h1><p>A network where a $5 meal, a needed mattress, a listening ear, or a first step toward work can matter. Built around the fourteen Catholic works of mercy, with a place for everyone willing to give or receive help.</p><div class="actions no-print"><button class="button primary" data-action="share-project">Copy the project link ↗</button><button class="button" data-action="print">Print / save as PDF</button><a class="button quiet" href="index.html">Explore the preview →</a></div><p class="print-only">Public preview: https://maestro-student777.github.io/endless-ai-product-realization/mercy/</p></div><aside class="project-note"><p>“I need help” and<br>“I have something to give”<br>can belong to the same person.</p><small>A principle of this project, expressed in our own words.</small></aside></section>
<div class="project-grid"><section class="project-panel"><div class="eyebrow">Available now</div><h2>Something you can explore.</h2><ul><li>A public website that opens without ChatGPT, an installation, or an account.</li><li>Nine example profiles, from a $5 meal to a $10,000 small business idea, plus gifts of time, items, and prayer.</li><li>Fourteen resource links, with practical help beside each story.</li><li>Personal need drafts and giving plans saved only on your own device.</li><li>A preview of direct and organization-coordinated help, with named or anonymous giving preferences.</li></ul></section><section class="project-panel dark"><div class="eyebrow">The next step</div><h2>A small pilot, with real care.</h2><p>Invite a willing parish, charity, or fiscal sponsor to shape a pilot together. Agree on who reviews requests, supports recipients, handles money, and reports how funds are used.</p><p>Then build the shared service around those decisions, beginning with one community and a manageable number of participants.</p><p><strong>Current stage:</strong> a working public preview. No organization has agreed to operate it yet, and no donations are being accepted here.</p></section></div>
<section aria-labelledby="funding-title"><div class="section-heading"><div><h2 id="funding-title">What support would help build next</h2><p>A practical sequence for discussing funding and responsibilities with a participating organization.</p></div></div><div class="milestones"><article class="milestone"><h3>Agree on the pilot</h3><p>Choose a community, name the responsible organization, define its role, and prepare a scoped budget with that organization.</p></article><article class="milestone"><h3>Connect real participants</h3><p>Add independent sign-in, a shared database, private request review, reporting, and a coordinator’s workspace.</p></article><article class="milestone"><h3>Make giving possible</h3><p>Set up approved payment and delivery arrangements, named or anonymous gifts, clear fees, and accurate records through the agreed operator.</p></article><article class="milestone"><h3>Learn and improve</h3><p>Run a small pilot, listen to recipients and donors, keep resource links current, and publish useful measures of help delivered.</p></article></div></section>
<div class="project-grid"><section class="project-panel"><h2>Ways to contribute</h2><p>Introduce a possible operating organization. Review the idea with someone who has asked for help. Offer design, accessibility, software, or community coordination experience.</p><p>People interested in funding can use this page to discuss the next milestones. A funding target can be set after the pilot scope, operator, and costs are agreed.</p></section><section class="project-panel"><h2>A network worth trusting</h2><p>People choose what to share. Requests get respectful review. Recipients are never required to perform gratitude or religious participation.</p><p>The future anonymous option would hide the donor from the recipient, while the responsible organization and payment provider retain the records they need.</p></section></div>
<section class="share-panel"><h2>Bring the idea into a conversation.</h2><p>Share this page with someone you care about. Ask: Would this be useful? What would help people feel respected? Do we know an organization that might want to shape a small pilot with us?</p><div class="actions no-print"><button class="button primary" data-action="share-project">Copy the project link</button><button class="button" data-action="print">Print / save as PDF</button><a class="button" href="https://github.com/Maestro-Student777/endless-ai-product-realization/tree/main/mercy" target="_blank" rel="noopener noreferrer">View the project on GitHub ↗</a></div></section>`;

const cornerPage = `<section class="intro"><div class="eyebrow">A little space of your own</div><h1>My corner.</h1><p>Keep a draft of what you need or a thought about how you could help. Come back to it when you are ready.</p></section><div class="device-note"><strong>Saved only in this browser.</strong> These drafts and plans are not published, sent to a recipient, or synced to another device. Anyone using this browser profile could see them. You can edit or remove them below.</div><div class="actions no-print"><button class="button primary" data-action="draft">+ Draft a need</button><button class="button quiet danger" data-action="clear-corner" id="clear-corner" disabled>Clear My corner</button></div><div class="corner-grid"><section><h2>My drafts <span class="tag" id="draft-total">0</span></h2><div id="saved-drafts"><noscript>Enable JavaScript to use personal drafts.</noscript></div></section><section><h2>My giving plans <span class="tag" id="plan-total">0</span></h2><div id="saved-plans"><noscript>Enable JavaScript to use personal giving plans.</noscript></div></section></div>`;

for (const [file,id,title,description,body] of [
 ['index.html','board','A little help. A real difference.','Explore a community care idea rooted in the fourteen works of mercy, with example needs and real resource links.',board],
 ['resources.html','resources','Find practical help','Find food, housing, furniture, work, caregiving, and faith resources on official organization websites.',resourcePage],
 ['works.html','works','The fourteen works of mercy','Discover the seven corporal and seven spiritual works of mercy and practical ways to care for a neighbor.',worksPage],
 ['project.html','project','Help build the Mercy Network','Share the Endless AI Mercy Network idea, explore the public preview, and discuss a pilot with a participating organization.',projectPage],
 ['my-corner.html','corner','Your personal corner','Save and revisit personal need drafts and giving plans on your own device.',cornerPage],
]) writeFileSync(output+file,layout(id,title,description,body));
console.log('Generated five public Mercy Network pages. No build dependencies or account required.');
