(()=>{'use strict';
const $=id=>document.getElementById(id),key='hotel-founder-chapter2-v1';
const contacts=[
{id:'score',name:'SCORE mentor matching',type:'Mentoring · start here',url:'https://www.score.org/find-mentor',detail:'Use your ZIP code to request a mentor. Mentoring is free. A specific mentor has not been assigned.',ask:'Could you help me compare buying a small B&B with learning through operations first, and identify one useful next step?',role:'Business mentor'},
{id:'sbdc',name:'Small Business Development Center',type:'Planning and funding',url:'https://www.sba.gov/local-assistance',detail:'Choose the center serving your proposed location. Ask about hospitality acquisitions, cash flow and lender preparation.',ask:'What information should I gather for a first feasibility and funding conversation about a small B&B?',role:'Small business adviser'},
{id:'mn-sbdc',name:'Minnesota SBDC',type:'Minnesota example · advising',url:'https://mn.gov/deed/business/help/sbdc/',detail:'Regional center finder. Use only if Minnesota is the location you want to explore.',ask:'Which regional center could help me test a small B&B concept and acquisition budget?',role:'Regional business adviser'},
{id:'sbao',name:'MN Small Business Assistance Office',type:'Minnesota example · registrations',url:'https://mn.gov/deed/business/help/sbao/',email:'smallbusiness@state.mn.us',phone:'651-556-8425',detail:'State starting-business guidance. Alternate phone: 800-310-8323.',ask:'Which state and local offices should I speak with about a small B&B, and where can I compare sole proprietor and LLC requirements?',role:'Business assistance adviser'},
{id:'alp',name:'Amy Cooley · ALP membership',type:'Owner network · education',url:'https://www.alplodging.org/contact-us/',email:'membership@alplodging.org',phone:'888-238-5508',address:'PO Box 622, Berlin, NJ 08009',detail:'Association of Lodging Professionals membership coordinator. Ask what aspiring-owner resources are available before choosing a paid membership.',ask:'Which resources or owner introductions would help someone exploring their first small B&B, and which are available without membership?',role:'Lodging association representative'},
{id:'think',name:'ThinkReservations Sales & Education',type:'Vendor · software and costs',url:'https://www.thinkreservations.com/company/contact-us',email:'sales@thinkreservations.com',phone:'877-736-4195',extension:'1',address:'1700 7th Ave, Ste 116 PMB 173, Seattle, WA 98101',detail:'Ask for a quote; no purchase is needed for this exercise. Published address is a mailing address.',ask:'Could you explain the setup, subscription and payment-processing costs for a hypothetical four-room B&B?',role:'Hotel software representative'},
{id:'license',name:'Lodging and food licensing office',type:'Minnesota example · approvals',url:'https://mn.gov/elicense/a-z/?id=1083-311223',detail:'Use the official entry point to identify MDH or the delegated local authority. Exact contact depends on the property location.',ask:'Who licenses this address, and what lodging, breakfast-service and ownership-change approvals would be needed?',role:'Licensing intake officer'},
{id:'local',name:'Local planning, building and fire offices',type:'Location needed · property use',url:'https://www.usa.gov/local-governments',detail:'Find the official city/county offices for the property. No local official is selected yet. Also request referrals to a lodging attorney, CPA and commercial insurer.',ask:'Is a B&B permitted at this parcel, and which guest-count, parking, building and fire requirements should I verify before considering it?',role:'Local planning intake officer'},
{id:'corpay',name:'Corpay Lodging hotel partnerships',type:'Solaris research · room networks',url:'https://www.corpaylodging.com/hotel-partners',detail:'Study an existing hotel network model through its official partner inquiry page. No Solaris relationship is established.',ask:'How does your hotel partner program handle rates, availability and payment, and which terms should an independent property review?',role:'Hotel network representative'},
{id:'hotelbeds',name:'Hotelbeds partner information',type:'Solaris research · distribution',url:'https://discover.hotelbeds.com/',detail:'Research distribution and partner requirements through the official site. No commercial terms are assumed.',ask:'What should a small independent property understand about inventory, distribution costs and cancellation terms before joining a network?',role:'Distribution representative'}
];
const steps=['Write a two-sentence B&B introduction.','Choose one mentor or resource contact.','Practice the conversation once.','Prepare or send one outreach message when ready.','Save one fact and one next question.'];
let state={version:1,checks:[],stages:{},notes:[],frontier:[],practices:[]};
function valid(x){return x&&x.version===1&&Array.isArray(x.checks)&&x.checks.length<=5&&x.checks.every(v=>typeof v==='boolean')&&x.stages&&typeof x.stages==='object'&&!Array.isArray(x.stages)&&Array.isArray(x.notes)&&x.notes.every(v=>typeof v==='string')&&Array.isArray(x.frontier)&&x.frontier.every(v=>typeof v==='string')&&Array.isArray(x.practices)&&x.practices.every(v=>v&&typeof v.date==='string'&&typeof v.contact==='string'&&Array.isArray(v.messages)&&v.messages.every(m=>m&&typeof m.who==='string'&&typeof m.text==='string'))}
try{const saved=JSON.parse(localStorage.getItem(key));if(valid(saved))state=saved}catch{}
function save(){try{localStorage.setItem(key,JSON.stringify(state));$('chapterStatus').textContent='Saved in this browser. Export a copy to keep or share.'}catch{$('chapterStatus').textContent='Browser storage is unavailable. Export your work before leaving.'}}
function el(tag,text,cls){const n=document.createElement(tag);if(text!==undefined)n.textContent=text;if(cls)n.className=cls;return n}
function link(text,url,cls){const n=el('a',text,cls);n.href=url;if(/^https:/.test(url)){n.target='_blank';n.rel='noopener'}return n}
function button(text,fn,cls='button secondary'){const n=el('button',text,cls);n.type='button';n.onclick=fn;return n}
function download(name,text,type='application/json'){const u=URL.createObjectURL(new Blob([text],{type})),a=link('',u);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),2000)}
function renderChecks(){$('checklist').replaceChildren();steps.forEach((s,i)=>{const l=el('label'),c=el('input');c.type='checkbox';c.checked=!!state.checks[i];c.onchange=()=>{state.checks=steps.map((_,j)=>j===i?c.checked:!!state.checks[j]);save();renderProgress()};l.append(c,el('span',s));$('checklist').append(l)});renderProgress()}
function renderProgress(){$('progressCount').textContent=state.checks.filter(Boolean).length+' of 5 steps recorded · A question is a useful start.'}
const stages=['Not contacted','Draft prepared','Contacted','Reply received','Follow-up needed'];
function vcard(c){const escape=s=>s.replace(/\\/g,'\\\\').replace(/\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');const fields=['BEGIN:VCARD','VERSION:3.0','FN:'+escape(c.name),'N:'+escape(c.name)+';;;;','URL:'+c.url];if(c.email)fields.push('EMAIL:'+c.email);if(c.phone)fields.push('TEL:'+c.phone);if(c.address)fields.push('NOTE:'+escape('Published mailing address: '+c.address));fields.push('END:VCARD');download(c.id+'.vcf',fields.join('\r\n')+'\r\n','text/vcard')}
function renderContacts(){const q=$('contactFilter').value.toLowerCase().trim();$('contactCards').replaceChildren();contacts.filter(c=>Object.values(c).join(' ').toLowerCase().includes(q)).forEach(c=>{const card=el('article',undefined,'chapter-card');card.append(el('span',c.type,'pill'),el('h3',c.name),el('p',c.detail),el('p','First question: '+c.ask,'contact-detail'));if(c.email)card.append(el('p',c.email,'contact-detail'));if(c.phone)card.append(el('p',c.phone+(c.extension?' · extension '+c.extension:''),'contact-detail'));if(c.address)card.append(el('p','Mailing address: '+c.address,'contact-detail'));card.append(link('Official source ↗',c.url,'contact-source'));const actions=el('div',undefined,'buttons');actions.append(button('Prepare outreach',()=>openDraft(c)),button('Practice',()=>startPractice(c)),button('Save contact',()=>vcard(c)));if(c.phone)actions.append(link('Call'+(c.extension?' · ext. '+c.extension:''),'tel:+1'+c.phone.replace(/\D/g,''),'button secondary'));card.append(actions);const label=el('label','Your outreach status'),select=el('select',undefined,'contact-stage');select.setAttribute('aria-label',c.name+' outreach status');stages.forEach(s=>{const o=el('option',s);o.selected=state.stages[c.id]===s;select.append(o)});select.onchange=()=>{state.stages[c.id]=select.value;save()};label.append(select);card.append(label);$('contactCards').append(card)});if(!$('contactCards').children.length)$('contactCards').append(el('p','No matching contact. Save the missing resource as a research task below.'))}
let draftContact;
function fillDraft(){const c=draftContact,name=$('senderName').value.trim()||'[Your name]',place=$('senderPlace').value.trim()||'a location I am still exploring';$('draftText').value='Hello,\n\nMy name is '+name+'. I’m exploring a small bed and breakfast in '+place+' and am at the early planning stage.\n\n'+c.ask+'\n\nIs there a suitable person or resource you could point me to? If a short introductory conversation is possible, please let me know what I should prepare.\n\nThank you,\n'+name;updateMail()}
function updateMail(){const c=draftContact;$('emailDraft').hidden=!c.email;if(c.email)$('emailDraft').href='mailto:'+c.email+'?subject='+encodeURIComponent('First B&B planning question')+'&body='+encodeURIComponent($('draftText').value)}
function openDraft(c){draftContact=c;$('draftTitle').textContent=c.name;$('contactPortal').href=c.url;$('draftStatus').textContent='Review this draft. Opening email or a contact page does not send it.';fillDraft();$('outreachDialog').showModal()}
$('refreshDraft').onclick=fillDraft;$('draftText').oninput=updateMail;
$('copyDraft').onclick=async()=>{try{await navigator.clipboard.writeText($('draftText').value);$('draftStatus').textContent='Copied. Paste into the official contact form or your email.';state.stages[draftContact.id]='Draft prepared';save();renderContacts()}catch{$('draftText').select();$('draftStatus').textContent='Select and copy the draft manually.'}};
function renderNotes(){$('noteList').replaceChildren();[...state.notes].reverse().forEach(n=>$('noteList').append(el('p',n)));$('frontierList').replaceChildren();state.frontier.forEach((n,i)=>{const li=el('li',n);li.append(button('Resolve',()=>{state.notes.push('Research task resolved: '+n);state.frontier.splice(i,1);save();renderNotes()},''));$('frontierList').append(li)});if(state.practices.length)$('noteList').append(el('p',state.practices.length+' practice transcript(s) saved. Included in Export.','hint'))}
$('saveChapterNote').onclick=()=>{const n=$('chapterNote').value.trim();if(!n)return;state.notes.push(new Date().toLocaleDateString()+': '+n);$('chapterNote').value='';save();renderNotes()};
$('saveFrontier').onclick=()=>{const n=$('frontierInput').value.trim();if(!n)return;state.frontier.push(n);$('frontierInput').value='';save();renderNotes()};
$('exportChapter').onclick=()=>download('hotel-founder-chapter2.json',JSON.stringify({...state,exported:new Date().toISOString(),contacts},null,2));
$('restoreChapter').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error('file too large');const x=JSON.parse(await f.text());if(!valid(x))throw Error('invalid format');if(!confirm('Replace Chapter 2 progress in this browser with this export?'))return;state={version:1,checks:x.checks,stages:x.stages,notes:x.notes,frontier:x.frontier,practices:x.practices};save();renderChecks();renderContacts();renderNotes()}catch{$('chapterStatus').textContent='Could not restore: choose a valid Chapter 2 JSON export under 2 MB.'}finally{e.target.value=''}};
function calculate(){const ids=['rooms','nights','occupancy','rate','variable','fixed'];if(ids.some(id=>!$(id).checkValidity()||$(id).value==='')){$('calcResult').textContent='Enter valid nonnegative amounts, 1–31 nights and occupancy between 0 and 100%.';return}const [r,n,o,a,v,f]=ids.map(id=>Number($(id).value)),sold=r*n*o/100,gross=sold*a,contribution=gross-sold*v-f;const money=x=>x.toLocaleString('en-US',{style:'currency',currency:'USD',maximumFractionDigits:0});$('calcResult').textContent=sold.toFixed(1)+' occupied room-nights · '+money(gross)+' gross room revenue · '+money(contribution)+' remaining before debt, owner pay, taxes and capital repairs.'}
['rooms','nights','occupancy','rate','variable','fixed'].forEach(id=>$(id).oninput=calculate);
$('contactFilter').oninput=renderContacts;
$('nexusCommand').onsubmit=e=>{e.preventDefault();const q=$('command').value.toLowerCase().trim();if(!q)return;const map={contacts:'contactDesk',mentor:'contactDesk',costs:'numbers',calculator:'numbers',notes:'knowledge',knowledge:'research',plan:'routeComparison',compare:'routeComparison',routes:'routeComparison',learn:'structures',company:'structures',frontier:'frontier'};if(q.includes('practice')){startPractice(contacts[0]);return}const target=Object.keys(map).find(k=>q.includes(k));if(target){$(map[target]).scrollIntoView({behavior:'smooth'});$('commandStatus').textContent='Opened '+target+'.'}else{$('frontierInput').value=$('command').value;$('frontier').scrollIntoView({behavior:'smooth'});$('commandStatus').textContent='New question? Review it in Frontier and save as a research task.'}};
let session=null,timer=null,recognition=null,speaking=false;
function speak(t){if(speaking&&'speechSynthesis'in window){speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.rate=.95;speechSynthesis.speak(u)}}
function addMessage(who,text){session.messages.push({who,text});const p=el('p');p.append(el('strong',who+': '),document.createTextNode(text));$('transcript').append(p);$('transcript').scrollTop=$('transcript').scrollHeight;if(who!=='You')speak(text)}
function startPractice(c){if(session)return;$('transcript').replaceChildren();$('practiceName').textContent=c.role;$('practiceReply').value='';$('practiceTime').textContent='00:00';session={contact:c.name,date:new Date().toISOString(),messages:[],step:0,started:Date.now(),resource:c};$('practiceHint').textContent='Guided role-play, not a provider answer. Mic permission is optional; browser speech services may process audio.';$('practiceDialog').showModal();addMessage('Practice guide','Let’s rehearse a conversation with a '+c.role.toLowerCase()+'. Introduce yourself and your B&B idea in two sentences.');timer=setInterval(()=>{const s=Math.floor((Date.now()-session.started)/1000);$('practiceTime').textContent=String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')},1000)}
$('sendPractice').onclick=()=>{if(!session)return;const t=$('practiceReply').value.trim();if(!t)return;$('practiceReply').value='';addMessage('You',t);session.step++;const prompts=[null,'You have put your idea into words. Now ask one question. Try: “'+session.resource.ask+'”','Good—keep that question for the real conversation. We cannot supply this organization’s answer here. Now ask who to speak with next, what to prepare, and when you can follow up.','You have rehearsed an introduction, a question and a next-step request. Write one thing you want to verify, then end and save. The real adviser can give situation-specific answers.'];addMessage('Practice guide',prompts[session.step]||'Save this as a question to verify with the real contact. You can end practice when ready. This script does not determine eligibility, legal requirements or provider policies.')};
function finishPractice(){if(!session)return;clearInterval(timer);timer=null;if(recognition){recognition.stop();recognition=null}if('speechSynthesis'in window)speechSynthesis.cancel();state.practices.push({contact:session.contact,date:session.date,messages:session.messages});session=null;save();renderNotes();$('practiceDialog').close();$('micPractice').textContent='Mic';$('chapterStatus').textContent='Practice saved in this browser and included in Export. No real call was made.'}
$('endPractice').onclick=finishPractice;$('closePractice').onclick=finishPractice;$('practiceDialog').addEventListener('cancel',e=>{e.preventDefault();finishPractice()});
$('speakerPractice').onclick=()=>{if(!('speechSynthesis'in window)){$('practiceHint').textContent='Voice playback is unavailable. Continue by typing.';return}speaking=!speaking;$('speakerPractice').setAttribute('aria-pressed',String(speaking));$('speakerPractice').textContent=speaking?'Voice on':'Voice off';if(speaking&&session)speak(session.messages[session.messages.length-1].text);else speechSynthesis.cancel()};
$('micPractice').onclick=()=>{const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){$('practiceHint').textContent='Speech recognition is unavailable in this browser. Type your reply below.';return}if(recognition){recognition.stop();return}if('speechSynthesis'in window)speechSynthesis.cancel();recognition=new SR();recognition.lang='en-US';recognition.onresult=e=>{if(session)$('practiceReply').value=e.results[0][0].transcript};recognition.onerror=()=>{$('practiceHint').textContent='Microphone unavailable or permission declined. You can still type.'};recognition.onend=()=>{recognition=null;$('micPractice').textContent='Mic'};try{recognition.start();$('micPractice').textContent='Stop mic';$('practiceHint').textContent='Listening. Review the transcript before pressing Reply.'}catch{recognition=null;$('practiceHint').textContent='Could not start microphone. Type your reply.'}};
document.querySelectorAll('[data-panel="practice"]').forEach(b=>b.onclick=()=>startPractice(contacts[0]));
renderChecks();renderContacts();renderNotes();calculate();
})();
